language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter

# Run tests
script:
     - pytest --cov=app
     - coveralls

after_success:
    - coveralls