language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter

# Run tests
script:
    - py.test  --cov-report term --cov=app/test/

after_success:
    - coveralls
    - codecov
